apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-zmyf
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jhutar-tenant/my-app/devfile-sample-python-basic-zmyf@sha256:69139c2538d3eef97a84fdde6bdd052b22f5260f362d23efb184c273640ee731
        name: my-python
        resources: {}
status: {}
